### ISSUE TITLE
HMR on Android: "TypeError: Attempting to change value of readonly property"

### ISSUE THREAD

**Issue by deepsweet** [callstack/haul#368] opened 2018-02-15 08:58 UTC
### Current Behavior

I've followed the HMR setup guide and HMR on Android fails with `TypeError: Attempting to change value of readonly property` while trying to apply changes. Works totally fine on iOS.

![screenshot](https://user-images.githubusercontent.com/266822/36248055-114da69e-122e-11e8-897d-e0b609dff71b.png)

### Expected Behavior

Should just work like on iOS :)

### Haul Configuration (webpack.haul.js)

```js
const path = require('path')

module.exports = ({ platform }, defaults) => ({
  entry: path.resolve('demo/'),
  resolve: {
    ...defaults.resolve,
    alias: {
      '~': process.cwd(),
    },
  },
})
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  v1.0.0-beta.13
| react-native     |  both 0.52.0 and 0.53.0
| node             | 8.8.1
| yarn      | 1.3.2

**Comment by zamotany** [comment] 2018-02-15 11:51
We are aware of this issue, but without a reproduction repository with the same dependencies are in your project, we cannot do much, so it would really help if you could create a repo.

**Comment by deepsweet** [comment] 2018-02-15 17:48
Unfortunately it's a rather complicated setup and private project. I'll try to extract something reproducible.

Also I can do some debugging on my side and provide results if you can guide me.

**Comment by zamotany** [comment] 2018-02-15 17:52
You can try logging `type` and `uniqueLocalName` by placing `console.log` here: https://github.com/callstack/haul/blob/master/src/hot/client/hotPatch.js#L59

There should be only logs of components, any other functions might be the ones breaking it, so please post them if you find any.

**Comment by sirajulm** [comment] 2019-02-17 16:16
### Current Behaviour
![image](https://user-images.githubusercontent.com/2260996/52915726-73a7c400-32fd-11e9-88f9-d943c61f70d1.png)

The same issue happens on both Android and iOS. Its seems like there is some issue with webpack, mixing of `export default` and `module.exports`
Below is more explainatory error when `Debug JS` is enabled

![image](https://user-images.githubusercontent.com/2260996/52915673-efedd780-32fc-11e9-86ac-4bb45781caf9.png)

### Haul Config
```
import { createWebpackConfig } from "haul";

export default {
  webpack: createWebpackConfig(({ platform }) => ({
    entry: `./index.js`
  }))
};
```

### Your Environment
software	version
Haul	`^1.0.0-rc.13`
react-native `0.58.4`
node `v11.6.0`
yarn	`1.13.0`

**Comment by stackdumper** [comment] 2019-02-28 11:15
Experiencing the same issue with a freshly initialized react-native project.

**Comment by sirajulm** [comment] 2019-02-28 15:38
@stackdumper This is the config file I got it working after few days of debugging

```
import { createWebpackConfig } from "haul";
import path from "path";

export default {
  webpack: (env, defaults) => {
    const config = createWebpackConfig({
      // ...defaults,
      entry: `./index.js`,
      resolve: {
        // ...defaults.resolve,
        alias: {
          // ...defaults.resolve.alias,
          react: path.join(__dirname, "node_modules/react"),
          "react-native": path.join(__dirname, "node_modules/react-native")
        }
      }
    })(env);

    config.module.rules = [
      {
        test: /\.js?$/,
        loaders: ["babel-loader"]
      },
      {
        test: /\.tsx?$/,
        loaders: ["babel-loader", "ts-loader"]
      },
      ...config.module.rules
    ];

    config.resolve.extensions = [
      ".ts",
      ".tsx",
      `.${env.platform}.ts`,
      ".native.ts",
      `.${env.platform}.tsx`,
      ".native.tsx",
      ...config.resolve.extensions
    ];

    return config;
  }
};

```
Main part in the config was the loaders, adding babel loader for js files, and ts-loader and babel-loader for tsx files fixed it for me.

**Comment by stackdumper** [comment] 2019-03-05 17:53
@sirajulm it doesn't help 😞

**Comment by stackdumper** [comment] 2019-03-05 17:54
Here's the reproduction:
https://github.com/stackdumper/haul-assign-readonly-repro.git

It is a clean `react-native init` -> `yarn haul init` setup, no typescript.

**Comment by sirajulm** [comment] 2019-03-06 04:18
@stackdumper 
This `haul.config.js` should fix your issue
```
import { createWebpackConfig } from 'haul';
import path from 'path';

export default {
  webpack: (env, defaults) => {
    const config = createWebpackConfig({
      entry: `./index.js`
    })(env);

    config.module.rules = [
      {
        test: /\.js?$/,
        loaders: ['babel-loader']
      },
      ...config.module.rules
    ];

    return config;
  }
};

```

I assume the `babel-loader` was not properly applied.

**Comment by stackdumper** [comment] 2019-03-08 09:30
@sirajulm thanks, this fixed the issue.

I guess the config you proposed should be a default, because currently `haul init` results in a broken project out-of-box.

**Comment by deepsweet** [comment] 2019-03-18 14:47
Managed to narrow it down to not re-transpile entire `node_modules/` with Babel:

```js
config.module.rules = [
  {
    test: /\.js$/,
    include: [
      path.resolve('node_modules/react-native/'),
      path.resolve('node_modules/metro/'),
      path.resolve('node_modules/react-devtools-core/'),
      path.resolve('node_modules/react-hot-loader/'),
    ],
    use: [
      {
        loader: 'babel-loader',
        options: {
          babelrc: false,
          presets: ['module:metro-react-native-babel-preset'],
          cacheDirectory: true,
        },
      },
    ],
  },
  // ...
]
```

**Comment by sirajulm** [comment] 2019-03-19 07:48
@deepsweet Thanks. but once quick doubt, why do we need to add `babelrc: false ` and add `          presets: ['module:metro-react-native-babel-preset']` to the webpack config? Is there any advantage or just a personal choice ?

**Comment by zamotany** [comment] 2019-08-12 13:59
Closing since in `@haul-bundler/cli` we dropped support for HMR and `haul` package in no longer supported

**Closed by zamotany** 2019-08-12 13:59 UTC
Labels: needs more info
