### ISSUE TITLE
Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by liujb** [callstack/haul#505] opened 2018-12-12 09:11 UTC
### Current Behavior

![](http://manhattan.didistatic.com/static/manhattan/do1_X5zkGJxiIk59kwkPLHzL)

### Expected Behavior

Expected not error.

### Haul Configuration (webpack.haul.js)

```
export default {
  webpack: createWebpackConfig(({ platform }) => ({
    entry: `./index.js`
  }))
};
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  v1.0.0-rc.10
| react-native     |  0.57.5
| node             |  v11.0.0
| npm or yarn      | 1.10.1

**Comment by yongching** [comment] 2018-12-13 04:05
I’m having this issue too, same environment.

**Comment by hslavax** [comment] 2018-12-13 04:37
I’m having this issue too, same environment. + 1

**Comment by thymikee** [comment] 2018-12-13 07:06
Can somebody provide a repro?

**Comment by liujb** [comment] 2018-12-13 07:30
@thymikee Sorry, could't provide repo now. When not use haul to start bundle server for android. App working correctly. 

I have setting haul.config.js like this, The problem is still.

```
import { createWebpackConfig } from "haul";
import path from 'path';

export default {
  webpack: createWebpackConfig(({ platform }) => ({
    entry: `./index.${platform}.js`,
    module: {
      rules: [
        {
          test: /\.js?$/,
          exclude: /(node_modules)/,
          include: [
            path.resolve(__dirname, './node_modules/react-navigation'),
            path.resolve(__dirname, './node_modules/query-string'),
            path.resolve(__dirname, './node_modules/strict-uri-encode'), 
            path.resolve(__dirname, './node_modules/decode-uri-component'),
            path.resolve(__dirname, './node_modules/react-navigation')
            path.resolve(__dirname, './node_modules/@react-navigation')
          ],
          use: {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env'],
              plugins: ['@babel/plugin-proposal-object-rest-spread']
            }
          }
        }
      ]
    },
    resolve: {
      modules: ["node_modules"],
      alias: {
        'react-navigation': 'react-navigation/src/react-navigation.js'
      }
    }
  }))
};

```

**Comment by liujb** [comment] 2018-12-13 07:31
> @liujb [react-navigation@1.x](mailto:react-navigation@1.x) is too old, i'm using [react-navigation@3.x](mailto:react-navigation@3.x)

react-navigation@3.x have the problem by using haul.

**Comment by thymikee** [comment] 2018-12-13 07:37
Ah, it's this issue again. Duplicate of https://github.com/callstack/haul/issues/502.

**Closed by thymikee** 2018-12-13 07:37 UTC

**Comment by thymikee** [comment] 2018-12-13 07:40
@liujb afaik there's no `@react-navigation` package, but `@react-navigation/core` and `@react-navigation/whatever-and-this-is-what-should-be-transpiled`. Again, as stated here https://github.com/callstack/haul/issues/502#issuecomment-443130900 feel free to send a PR adding this to Haul, because `react-navigation` is quite popular in RN ecosystem. I'm happy to merge it :)

**Comment by liujb** [comment] 2018-12-13 08:47
@thymikee thanks for your help.
