### ISSUE TITLE
Images are not loading with @haul-bundler

### ISSUE THREAD

**Issue by aaronkchsu** [callstack/haul#593] opened 2019-07-16 14:13 UTC
## Ask your Question
I followed the migration instructions and copied my old config into the transform of the new haul config.

Everything is working pretty well except in places where I require images using the relative path haul doesn't go to the right location to fetch them. Is there a way for me to fix this?

```
info ▶︎ RESOLVED FILE: /USERS/AARONKCHSU/CODE/BLERP/MOBILE/SRC/IMG/NEW-STOP-ICON.PNG <--> /USERS/AARONKCHSU/CODE/BLERP/MOBILE/SRC/IMG/NEW-STOP-I
CON.PNG
info ▶︎ RESOLVED FILE: /USERS/AARONKCHSU/CODE/BLERP/MOBILE/SRC/IMG/NEW-SPAM-ICON.PNG <--> /USERS/AARONKCHSU/CODE/BLERP/MOBILE/SRC/IMG/NEW-SPAM-I
CON.PNG
```
```
GET /assets/ios/src/img/default_image.png 404
GET /assets/ios/src/img/default_image.png 404
GET /assets/ios/src/img/default_image.png 404
GET /assets/ios/src/img/default_image.png 404
GET /assets/ios/src/img/heart-unselect.png 404
GET /assets/ios/src/img/ios-share.png 404
GET /assets/ios/src/img/new-play-icon.png 404
GET /assets/ios/src/img/default_image.png 404
GET /assets/ios/src/img/heart-unselect.png 404
GET /assets/ios/src/img/new-play-icon.png 404
GET /assets/ios/src/img/heart-unselect.png 404
GET /assets/ios/src/img/heart-unselect.png 404
GET /assets/ios/src/img/ios-share.png 404
GET /assets/ios/src/img/new-play-icon.png 404
GET /assets/ios/src/img/heart-unselect.png 404
GET /assets/ios/src/img/heart-unselect.png 404
GET /assets/ios/src/img/ios-share.png 404
GET /assets/ios/src/img/ios-share.png 404
GET /assets/ios/src/img/heart-unselect.png 404```

```

```
GET /assets/android/src/img/android-share.png 404
GET /assets/android/src/img/new-play-icon.png 404
GET /assets/android/src/img/heart-unselect.png 404
GET /assets/android/src/img/android-share.png 404
GET /assets/android/src/img/new-play-icon.png 404
GET /assets/android/src/img/android-share.png 404
GET /assets/android/src/img/heart-unselect.png 404
GET /assets/android/src/img/new-play-icon.png 404
GET /assets/android/src/img/android-share.png 404
GET /assets/android/src/img/heart-unselect.png 404
GET /assets/android/src/img/default_image.png 404
GET /assets/android/src/img/default_image.png 404
GET /assets/android/src/img/new-play-icon.png 404
GET /assets/android/src/img/heart-unselect.png 404
GET /assets/android/src/img/android-share.png 404
GET /assets/android/src/img/new-play-icon.png 404
GET /assets/android/src/img/heart-unselect.png 404
GET /assets/android/src/img/default_image.png 404
GET /assets/android/src/img/default_image.png 404
GET /assets/android/src/img/android-share.png 404
GET /assets/android/src/img/new-play-icon.png 404
GET /assets/android/src/img/heart-unselect.png 404
GET /assets/android/src/img/new-play-icon.png 404
GET /assets/android/src/img/android-share.png 404```

**Comment by zamotany** [comment] 2019-07-16 15:15
@aaronkchsu 
Can you describe file structure in your project? More specifically: where the images are located, from where they are required and what the import/require path used. No need to post all of those, just some examples.

**Comment by zamotany** [comment] 2019-07-16 16:08
I have check it and it's a bug. I'm working on a fix.

**Comment by zamotany** [comment] 2019-07-17 12:23
@aaronkchsu the issue is now fixed and will be released in `0.7.1` today.

**Closed by zamotany** 2019-07-17 12:23 UTC
Labels: bug

**Comment by aaronkchsu** [comment] 2019-07-17 13:24
@zamotany thank you so much!

**Comment by zamotany** [comment] 2019-07-17 16:38
@aaronkchsu `0.8.0` is live on npm with some improvements
