### ISSUE TITLE
Haul crashes after upgrading from beta to 1.0-rc (zlib related)

### ISSUE THREAD

**Issue by Strate** [callstack/haul#429] opened 2018-05-04 13:23 UTC
After compilation success, haul server crashes with:

```
haul/src/server/index.js:58                                                                                                                                   
    throw err;
    ^

Error: invalid block type
    at InflateRaw.zlibOnError (zlib.js:153:15)
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  haul@1.0.0-rc.0
| react-native     |  react-native@0.55.3
| node             | v8.11.1
| npm or yarn      | 5.8.0

**Comment by thymikee** [comment] 2018-05-04 22:26
Try to remove `node_modules/.cache` and run it again

**Comment by Strate** [comment] 2018-05-07 06:29
@thymikee just tried, and this doesn't help.
I've completely reinstalled `node_modules`, and removed `~/.npm` cache.

**Comment by jukben** [comment] 2018-05-09 11:42
Could you please measure your bundle size? I've encountered this as well in dev mode I was working on the project with 50 Mb bundle size. 

I'm planing to investigate more, next step I'd like to take is to disable Webpack's uglify plugin, because it could be some regression (between Webpack 3 and Webpack 4).

**Comment by thymikee** [comment] 2018-05-16 11:05
Just a note from our internal discussion: we're still not sure why this issue happens, but it may be connected with big bundle size in development, which is due to inline source-maps we add for Chrome remote debugging. We'll work on making external source-maps work with Chrome, so that we can drop inlining.

**Comment by jukben** [comment] 2018-05-18 14:40
As bundle (with dev config) works fine. So I thought there is an issue with sending this over WS. I have to test it more.

**Comment by jukben** [comment] 2018-05-23 13:53
Fixed in https://github.com/callstack/haul/pull/434

**Closed by jukben** 2018-05-23 13:53 UTC
Labels: 1.0 RC, bug
