### ISSUE TITLE
After app refresh it got not updated bundle (cache?)

### ISSUE THREAD

**Issue by Natteke** [callstack/haul#705] opened 2020-02-21 11:31 UTC
## Environment
MAC OS 10.14.6

```
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@haul-bundler/babel-preset-react-native": "^0.16.0",
    "@haul-bundler/preset-0.60": "^0.17.0",
    "@haul-bundler/cli": "^0.17.0",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.9.0"
  },
```
```
module.exports = {
  presets: ['module:@haul-bundler/babel-preset-react-native'],
};
```

```
import {withPolyfills, makeConfig} from '@haul-bundler/preset-0.60';

export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills('./index'),
    },
  },
});

```

## Description
After launching app, changing code and refreshing it in simulator (cmd + r), nothing happens.
Looks like bundler always sends an initial bundle, and do not updating it.
If i kill bundle process and re-launch it, i will see an updated code.

## Reproducible Demo

I have faced this issue with completely new project.
1) do react-native init App
2) install "haul" according to "Getting started" documentation
3) change App.js
4) press refresh

==================================
1) open simulator
![image](https://user-images.githubusercontent.com/24633723/75030791-ec63d200-54b5-11ea-8da6-5c67ed221b64.png)

2) change code
3) press refresh
![image](https://user-images.githubusercontent.com/24633723/75030839-0ac9cd80-54b6-11ea-8a69-c0bac40146a8.png)

Nothing...

5) kill process
![image](https://user-images.githubusercontent.com/24633723/75030910-32b93100-54b6-11ea-8624-e8f57b5c36d7.png)

6) Repeat
![image](https://user-images.githubusercontent.com/24633723/75030956-482e5b00-54b6-11ea-9f97-c409a38c0411.png)

**Comment by zamotany** [comment] 2020-02-21 12:11
Yup, something is wrong. It looks like it's not watching for changes.

**Comment by jgornick** [comment] 2020-02-23 03:18
@zamotany Any chance you might be able to point me in the right direction so that I could try to figure out the issue?

**Comment by Natteke** [comment] 2020-02-23 07:43
@zamotany, hi again!
Is there some workaround to use haul right now with react 61.5?
Looks like haul v16 does not work with it, so....

Can you suggest something how to work, till it is not fixed? :D

**Comment by zamotany** [comment] 2020-02-24 17:53
@jgornick I suggest first to try downgrading to 0.15.0. There was huge dependency update, which might have broken it.

When I was testing it myself, it looked like the webpack wasn't picking up the changes to the file. Compiler status should changes from idle -> running -> idle but it never did. You can try adding some console logs here to see if the event was emitted from the compiler: https://github.com/callstack/haul/blob/master/packages/haul-core/src/server/Server.ts#L71 - it will be emitted initially for initial compilation and should for the rebuild as well. You can add console log here as well: https://github.com/callstack/haul/blob/master/packages/haul-core-legacy/src/compiler/worker/runWebpackCompiler.js#L198

**Comment by Natteke** [comment] 2020-02-28 07:08
This looks like a minor issue, but the dev process without reload is a real pain :c

**Comment by Natteke** [comment] 2020-02-28 09:20
The problem was solved after creating custom babel config according to the [recipe](https://github.com/callstack/haul/blob/master/docs/Recipes.md).
Now after saving file haul recompiles bundle, and after app refresh you see the changes without killing/reloading haul process.

@zamotany, @jgornick, i assume that the problem lies in default `config.module.rules`,
hope this will help in investigation.

At least we found workaround to develop with haul without a pain

```
export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills('./index.ts'),
      transform({ config }) {
        config.module.rules = [
          {
            test: /\.tsx?$/,
            exclude: '/node_modules/',
            use: [
              {
                loader: 'babel-loader',
              },
              {
                loader: 'ts-loader',
              }
            ]
          },
          ...config.module.rules,
        ];
      },
    },
  },
});
```

**Comment by zamotany** [comment] 2020-04-29 13:32
Closing this issue. We've confirmed that this is no longer happening (at least with the default config).

**Closed by zamotany** 2020-04-29 13:32 UTC
Labels: bug
