### ISSUE TITLE
HMR does not work with React Native 0.49 

### ISSUE THREAD

**Issue by jurajkrivda** [callstack/haul#303] opened 2017-11-27 14:48 UTC
I use React Native Navigation. When I do `import 'haul/hot/patch';` in my index.js I am getting 
`undefined is not an object (evaluating slot[i].key)` etc.

**Comment by thymikee** [comment] 2017-11-27 15:32
Have you seen the [Manual Setup](https://github.com/callstack/haul/blob/master/docs/hmr/Setup.md#manual-setup) guide? Also, make sure you turn off Live Reload, when using HMR

**Comment by Krizzu** [comment] 2017-11-27 15:53
This is hopefuly fixed in #292

**Comment by jurajkrivda** [comment] 2017-11-27 18:01
@Krizzu still error with #master. 
@thymikee yes of course I followed this tutorial https://github.com/callstack/haul/blob/master/docs/hmr/guides/react-native-navigation.md

**Comment by Krizzu** [comment] 2017-11-28 06:46
Hey @jurajkrivda 
Could You please post full error (maybe a screenshot)? Thanks!

**Comment by zamotany** [comment] 2017-11-28 09:38
@Krizzu 
If the error is `undefined is not an object (evaluating slot[i].key)` and haul is from master/latest, it means that there's a module @jurajkrivda project that is breaking proxied components map. We can provide some guidance no how to find the breaking module, but it would be better if we had access to source.

@jurajkrivda 
Can you post what dependencies are you using (from `package.json`)?

**Comment by Krizzu** [comment] 2017-11-28 09:49
@zamotany That's why I want to see a ss from `red-box`, so we can track it down. But yeah, source code would be better to debug, although I'm not convinced that @jurajkrivda's project is OS

**Comment by jurajkrivda** [comment] 2017-11-28 10:11
@zamotany 

```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "^8.0.1",
    "babel-jest": "^21.2.0",
    "babel-plugin-module-resolver": "^3.0.0",
    "babel-preset-react-native": "^4.0.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "^4.8.0",
    "eslint-config-dacz": "^3.0.0",
    "eslint-import-resolver-babel-module": "^4.0.0-beta.3",
    "eslint-plugin-ava": "^4.2.2",
    "eslint-plugin-compat": "^2.0.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
    "jest-expo": "^21.0.2",
    "mocha": "^4.0.1",
    "prettier-eslint": "^8.2.0",
    "prop-types": "^15.6.0",
    "react-dom": "^16.0.0",
    "react-native-debugger-open": "0.3.15",
    "react-test-renderer": "16.0.0",
    "reactotron-react-native": "^1.12.3"
  },
  "scripts": {
    "android:dev": "cd android && ./gradlew installDebug",
    "android:prod": "react-native run-android --variant release",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "build:android": "haul bundle --platform android --entry-file index.android.js --bundle-output build/index.android.bundle --assets-dest build --dev false",
    "start": "haul start"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "apollo-cache-inmemory": "^1.1.1",
    "apollo-client": "^2.0.3",
    "apollo-client-preset": "^1.0.3",
    "apollo-link": "^1.0.3",
    "apollo-link-http": "^1.2.0",
    "apollo-link-set-context": "^0.5.4",
    "deep-equal": "^1.0.1",
    "graphql": "^0.11.4",
    "graphql-tag": "^2.4.2",
    "graphql-tools": "^2.2.1",
    "haul": "git+https://github.com/callstack/haul.git#master",
    "lottie-react-native": "2.2.7",
    "moment": "2.19.1",
    "ramda": "0.25.0",
    "react": "16.0.0",
    "react-apollo": "^2.0.1",
    "react-native": "0.49.3",
    "react-native-action-button": "^2.8.0",
    "react-native-android-statusbar": "^0.1.3",
    "react-native-calendars": "^1.11.0",
    "react-native-code-push": "5.1.3-beta",
    "react-native-config": "^0.10.0",
    "react-native-datepicker": "^1.6.0",
    "react-native-elements": "^0.18.2",
    "react-native-fcm": "^10.0.1",
    "react-native-i18n": "2.0.9",
    "react-native-modalbox": "^1.4.2",
    "react-native-navigation": "^1.1.253",
    "react-native-platform-touchable": "^1.1.1",
    "react-native-splash-screen": "^3.0.1",
    "react-native-svg": "^6.0.0",
    "react-native-vector-icons": "4.4.2",
    "react-redux": "^5.0.6",
    "recompose": "0.26.0",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "validate.js": "^0.12.0",
    "victory-native": "^0.16.1"
  }
}
```

**Comment by jurajkrivda** [comment] 2017-11-28 10:17
@Krizzu I use navigation from WIX. I started with this in my index.js:

```
import 'haul/hot/patch';
import './src';
```

![screenshot_20171128-111521](https://user-images.githubusercontent.com/1255836/33314346-a5920cc6-d42d-11e7-8051-cfb65ab059d6.png)

**Comment by Krizzu** [comment] 2017-11-28 10:45
@jurajkrivda Thanks for your input!
I think we've localized the issue. We'll try to push fix today!

**Comment by zamotany** [comment] 2017-12-11 11:21
@jurajkrivda Can you install Haul from this commit `https://github.com/callstack/haul#f8d087e49401874ab8ceed2bf559b649f9fbc0ed`? We cannot reproduce your error, so we need you to check if the fix is working fine.

**Comment by hedgepigdaniel** [comment] 2018-01-21 23:30
#316 fixes this issue for me

**Closed** 2018-01-22 10:06 UTC
Labels: has PR

**Comment by lavaxun** [comment] 2018-03-07 17:12
I encountered HMR issue after I pinned RN version to 0.51 in Windows 10. 
Also tested across few environments and I found this strange behaviour. 

1. ios + hot reload + rn 0.53 + mac = **working**
2. android + hot reload + rn 0.53 + mac = **not working**
3. android + hot reload + rn 0.51 + mac = **working**
4. android + hot reload + rn 0.51 + windows = **not working**

current react native version is: **16.2.0**
haul version: **1.0.0-beta.13**
react-native-navigation version: **1.1.398**

everything is working fine if I commented out the `import 'haul/hot/patch` from the entry file.


![screen shot 2018-03-08 at 12 58 25 am](https://user-images.githubusercontent.com/1982412/37106739-8bbed322-226d-11e8-8dde-430bd7bab6c2.png)
