### ISSUE TITLE
Haul overrides process enviroments variables

### ISSUE THREAD

**Issue by krystiansliwa** [callstack/haul#428] opened 2018-05-04 12:50 UTC
Hi, 
I found an issue for me in the newest haul. 
I cannot access any process environment variables. I have only haul specific envs like: HAUL_PLATFORM, HAUL_DIRECTORY, HAUL_OPTIONS, HAUL_SOCKET_ADDRESS.

### Current Behavior
When I run haul from _package.json_ script using yarn like below
`yarn run server:android:dev` 

script in _package.json_
`"server:android:dev": "NODE_ENV=development haul"`

Then I get undefined for  call `process.env.NODE_ENV` in _webpack.config.js_ file.

### Expected Behavior

I should have access to passed environment variables.

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.0
| react-native     |  0.55.3
| node             | v9.7.1
| npm or yarn      | 1.5.1

**Comment by FredyC** [comment] 2018-05-04 13:01
The fix was merged just yesterday. I think it's not released yet. https://github.com/callstack/haul/pull/426

**Comment by zamotany** [comment] 2018-05-04 14:24
Duplicate of #425 fixed in #426. Will be released soon 😉

**Closed by zamotany** 2018-05-04 14:24 UTC

**Comment by krystiansliwa** [comment] 2018-05-04 18:25
Ok thanks for the info ;)
